---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install --no-lockfile --non-interactive

before_script:
  - greenkeeper-lockfile-update

script:
  - npm test

after_script:
  - greenkeeper-lockfile-upload
